### ISSUE TITLE
Esboço da Tela de Login

### ISSUE THREAD

**Issue by Mossatto** [Mossatto/Oncinha#2]
RGB:
Amarelo: 255/203/0
Verde: 0/148/64
Azul: 48/38/129

**Comment by gkarkoski** [comment]
Não criei o pullrequest aqui p não zuar com tudo, pelo figma ta na mão.

https://www.figma.com/design/heouWQAowCjQZo12yIdtrc/esbocoLogin?node-id=2-4&node-type=FRAME&t=pejpKFxrTjQd3mJI-0
